version: '3.9'
services:
  postgres_todo_db:
    image: postgres:latest
    container_name: postgres_todoapi_1
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      PGDATA: /var/lib/postgresql2/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "todo_db", "-U", "todo_user"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - todoapi_default

  app:
    container_name: todo_api_container
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_todo_db
    networks:
      - todoapi_default
    env_file: .env  # Load environment variables from the .env file

networks:
  todoapi_default:
    driver: bridge
